### ISSUE TITLE
Not compatable with linq

### ISSUE THREAD

**Issue by dtaylor-530** [kaosborn/KaosCombinatorics#1]
Perhaps worth noting that the package is not compatable with LINQ in the Readme. Thanks

**Comment by dtaylor-530** [comment]
I made a gist with extension methods to use with Linq
https://gist.github.com/dtaylor-530/442b4ca4f8a92b513b29c47affda38a9

**Comment by kaosborn** [comment]
First, thanks for the feedback. It's nice to know someone has at least tried using my library.

So I'm curious to see an example where you can't use LINQ by just including `.GetRows()` in your expression. I have a few contrived examples that successfully use LINQ expressions but it would help me to understand how you are using it that would necessitate your extensions.

By the way, a little background:

You probably already noticed that the default iterator for every class is to produce the elements, not the rows of sequences. The rationale was because of symmetry:
* `GetRows` is similar to methods `GetRowsForAllChoices`, `GetRowsForAllPicks` while there is only one style of getting elements.
* The indexers return sequence elements and it seemed the default iterator should match the indexer.

I know that iterating sequence rows is more common than iterating elements but these two points led to the current design.

**Comment by dtaylor-530** [comment]
sorry i wouldn't have said anything if i hadn't thought the project was worth it.
It seems i was too hasty. I tried to replicate the problem and it seems i got caught out by the lazy loading. 
In the watch window it looks as though all the sequences are the same. 
I improved the gist file. It has methods for making sets with completely unique elements. I don't know if you're interest.
Thanks for the response.
